doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                metadata_cache_driver: apc
                query_cache_driver:
                  type: memcached
                  host: localhost
                  port: 11211
                  instance_class: Memcached
                result_cache_driver:
                  type: memcached
                  host: localhost
                  port: 11211
                  instance_class: Memcached

                mappings:
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~