fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

    registration:
        confirmation:
            from_email:
                address:        julio.antunez.tarin@gmail.com
                sender_name:    Jat Laboratory
            enabled:    true