jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
#        "FOS\UserBundle\Model\UserInterface": sha512
        "Application\Sonata\UserBundle\Entity\User":  sha512
        "Application\Sonata\UserBundle\Entity\Group": sha512

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            switch_user:        true
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                check_path:     sonata_user_admin_security_check
                default_target_path: sonata_admin_dashboard
                failure_path:   null
                use_forward:    false
            logout:
                path:           sonata_user_admin_security_logout
                target:         sonata_user_admin_security_login
            remember_me:
                key:            randomvalue987654321
                lifetime:       604800
            anonymous:          true

        # defaut login area for standard users
        main:
            pattern:            .*
            switch_user:        true
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
                default_target_path: jat_frontend_home
                failure_path:   null
                use_forward:    false
                success_handler:  auth.success_handler
            logout:
                path:           fos_user_security_logout
                target:         fos_user_security_login
            remember_me:
                key:            randomvalue123456789
                lifetime:       604800
            anonymous:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -> custom access control for the admin area of the URL
        - { path: ^/(en|es)/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end

        - { path: ^/(en|es)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/(en|es)/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT