parameters:
    # acl
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\Model\UserAdmin

services:

#  sonata.admin.extension:
#      class: Application\Sonata\UserBundle\Admin\Model\UserAdmin
#      tags:
#          - { name: sonata.admin.extension, target: sonata.user.admin.user }
#      arguments: [null, Application\Sonata\UserBundle\Entity\User, ApplicationSonataUserBundle:UserAdmin ]

#  twig.extension.debug:
#    class: Twig_Extensions_Extension_Debug
#    tags:
#    - { name: twig.extension }

  twig.text_extension:
          class: Twig_Extensions_Extension_Text
          tags:
              - name: twig.extension

  application_sonata_user.twig.extension.debug:
      class: Twig_Extension_Debug
      tags:
           - { name: 'twig.extension' }
